### PR TITLE
feat: generate shell completions

### LINKED ISSUE #2: Generate shell completion scripts rather than manually maintaining them
Generate shell completion scripts using [clap_complete](https://crates.io/crates/clap_complete). This would make it easier to keep the completion scripts up to date with any changes to handlr's arguments as well as support other shells.

Ideally, a solution should use build.rs or cargo xtask and leverage the existing `Cmd` struct.

# To do:
- [ ] Implement completion generation in cargo xtask
- [ ] Update GitHub Actions

### PR DESCRIPTION
**Pull request by Anomalocaridid**
Makes completion scripts generated on the fly rather than manually maintained. However, rather than being generated at build time, it is generated by running `COMPLETE=<shell> handlr` where `<shell>` is the name of the shell.

This approach can still be used for generating scripts when packaging `handlr-regex` by redirecting stdout to a file. Also it technically expands completion support to include elvish and powershell, but I have not tested them.

It should be stressed that this relies on currently-unstable behavior of `clap_complete`.

I also added a nix flake because this was annoying to test otherwise.

Closes #2.

### CODE REVIEW

**Comment by akinomyoga** [comment]
What is the expected usage of this feature? I thought it was supposed to be used as e.g. `eval "$(COMPLETE=bash handlr)"`, but the usage is not documented anywhere.

> This approach can still be used for generating scripts when packaging `handlr-regex` by redirecting stdout to a file. Also it technically expands completion support to include elvish and powershell, but I have not tested them.

This caused a problem [1,2] when packaging `handlr-regex`. How should one do this properly? Since the output of `COMPLETE=bash handlr` contains *the absolute path to the binary that was used to generate it*, the generated scripts would contain the path to the binary file in the *build directory*. To properly generate the scripts, one needs to replace the binary file in the building system, which is unusual.

- [1] https://github.com/akinomyoga/ble.sh/issues/521
- [2] https://gitlab.archlinux.org/archlinux/packaging/packages/handlr-regex/-/issues/1

The behavior of using the absolute path is not a problem. It would actually be preferable to ensure the consistency between the completion setting and the actually used binary in the case when there are multiple versions of `handlr` in the system and the user changes `PATH`.

What are the package maintainers supposed to handle this? Do we need to manually modify the generated script files? Or we shouldn't generate the script files in the build process and instead instruct the users to write the one-line setting in their `~/.bashrc`? Or should we put `eval "$(COMPLETE=bash handlr)"` instead of dumping the result of `COMPLETE=bash handlr`?

I'm sorry if I missed existing documentation about this.

**Comment by Anomalocaridid** [comment]
@akinomyoga Sorry, pretty big oversight on my part. I completely missed that the completion scripts hard-code the binary's location. Most likely because I pretty much exclusively use NixOS, where that's not a big deal.

I cannot find any way to change this behavior, so I would say putting `eval "$(COMPLETE=bash handlr)` (and other shells' equivalents) in the completion scripts instead of generating them would probably be the best bet, and failing that, instructing users to put it in their `~/.bashrc` (or their shell's equivalent)

I will make sure to update README.md regarding this soon. Sorry for any inconvenience I caused.

**Comment by akinomyoga** [comment]
Thank you for your quick reply! Thank you also for your thoughts about the usage.

**Comment by Anomalocaridid** [comment]
@akinomyoga I took a look at `handlr-regex`'s `PKGBUILD` and thought of another thing you might want to consider.

If possible, you might want to consider generating the completion scripts in `package()`, after the `handlr` binary has been installed, rather than in `build()`.

For reference, [`handlr-regex`'s Nix package](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ha/handlr-regex/package.nix#L48) uses a similar approach, which is probably the reason it works fine in NixOS.

**Comment by Celti** [comment]
You can't actually properly call it from its installed location in `package()` because the package still isn't actually installed at that point — you'd get something like `/build/handlr-regex/pkg/usr/bin/handlr` instead, which is still the same problem.

**Comment by Anomalocaridid** [comment]
> You can't actually properly call it from its installed location in `package()` because the package still isn't actually installed at that point — you'd get something like `/build/handlr-regex/pkg/usr/bin/handlr` instead, which is still the same problem.

Thanks for pointing this out! I erroneously assumed `$pkgdir` was the package's install directory. In hindsight that way of doing things doesn't make sense outside of nix.

**Pull request merged**
